# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run crawler
      run: |
        cd crawler
        python -m scrapy crawl quotes
    - name: List files in directory
      run: |
        cd ..
        ls -lR
    - name: Upload crawled data and scrapy log
      uses: actions/upload-artifact@v2
      with:
        path: 
          data/*.csv
        retention-days: 5
